Closes #26
pdybowski/breaking-news pull request #29
Opened 2020-12-26 06:45 UTC by hoolek77

Configured webpack + babel and did some minor changes to directory structure.

2020-12-26 08:56 UTC, pdybowski requested changes
troszkę do zmiany/poprawy

2020-12-26 08:56 UTC, pdybowski commented on dist/index.html
> +<!DOCTYPE html>
Folder 'dist' lub 'build' (zależy jak nazwiesz) powinien znaleźc się na liście igonorowanych przez gita

2020-12-26 08:56 UTC, pdybowski commented on webpack.config.js
> +  mode: 'development',
mode - nie jest potrzebny na razie (pobawimy się z tym przy późniejszych projektach)
trzeba dodać jeszcze obiekt 'entry' oraz 'output'.

2020-12-26 08:56 UTC, pdybowski commented on webpack.config.js
> +    rules: [
trzeba dodać rules dla:

- css
- png|jpe?g|gif|ico
- svg|eot|ttf|woff|woff2

2020-12-26 08:56 UTC, pdybowski commented on package.json
> +        "start": "webpack serve",
dla start: "webpack-dev-server --watch --open"
dla build: "webpack"

2020-12-26 11:53 UTC, pdybowski requested changes

2020-12-26 17:40 UTC, pdybowski approved these changes

2020-12-26 19:29 UTC, bartoszbialecki commented on package.json
> +    "babel-loader": "^8.2.2"
Zależności dotyczące babela powinny też pójść do devDependencies

2020-12-26 19:37 UTC, bartoszbialecki commented on src/index.html
> +    <script type="module" src="index.js" defer></script>
Jeśli w webpacku mamy output main.js w katalogu dist to tutaj powinniśmy chyba użyć tego właśnie skryptu. 
Można też zrobić, aby webpack sam doklejał skrypt do index.html wtedy można by tag <script> usunąć stąd.

2020-12-26 19:48 UTC, bartoszbialecki commented on webpack.config.js
> +}
Nie wiem czy nie powinniśmy albo rozdzielić konfiguracji webpacka na dwa, osobno dla trybu development i osobno dla production albo zrobić jedną konfigurację ale sprawdzać tam w jakim trybie jesteśmy i odpowiednio dostosować reguły. Np. w wersji production powinniśmy kompresować pliki ale w wersji development nie powinniśmy tego robić, bo to utrudnia debugowanie itp.

2020-12-26 20:09 UTC, pdybowski commented on webpack.config.js
> +}
Może na razie skupmy się na kodzeniu w JSie. Jak zostanie czas to zmienimy webpacka. Chyba że ktoś będzie miał chwile to niech zrobi fixa. Webpack nie jest najważniejszy teraz

2020-12-26 20:26 UTC, pdybowski commented on src/index.html
> +    <script type="module" src="index.js" defer></script>
https://webpack.js.org/plugins/html-webpack-plugin/

tworzenie index.html i 'doklejanie' index.js 
usuń wtedy CopyPlugin - nie będzie potrzebny
usuń skrypt z head tag w index.html

2020-12-26 20:33 UTC, pdybowski reviewed
Sprawdz komentarze od Bartka

2020-12-27 16:14 UTC, bartoszbialecki approved these changes

2020-12-27 16:22 UTC, merged