implementation home page and create navigation
pdybowski/breaking-news pull request #30
Opened 2020-12-29 18:06 UTC by ibednorz

2020-12-29 19:58 UTC, bartoszbialecki commented on src/content/styles/global.css
> +}
Ja bym w tym pliku trzymał tylko globalne style, czyli te dla html, body, wspólne dla np. linków, przycisków itp. i nie importował tutaj styli dla komponentów np. header, footer itd. tylko te style był importował w pliku js dotyczącego tego komponentu, czyli np. w index.js w katalogu header bym importował wszystkie style dotyczące tego nagłówka. Webpack wtedy powinien zająć się zaimportowaniem css. 
To tylko sugestia, można zostawić jak jest, tylko wtedy każdy kto robi jakiś komponent będzie musiał ciągle zmieniać ten plik, żeby dodać swoje style.

2020-12-29 19:59 UTC, bartoszbialecki commented on src/content/styles/global.css
> +  color: var(--text);
Zmienna --text nie została nigdzie zdefiniowana.

2020-12-29 20:01 UTC, bartoszbialecki commented on src/index.html
> +    <link rel="stylesheet" href="./content/styles/global.css" />
Nie dodawałbym styli ręcznie tutaj, tylko w pliku js, wtedy webpack może dodać je za nas. Np., można ten global.css importować w index.js, który jest wejściem do naszej aplikacji.

2020-12-29 20:02 UTC, bartoszbialecki commented on src/index.html
> +    <main>
main powinien zawierać główny content, header, nav, footer itp. powinny być poza main

2020-12-29 20:05 UTC, bartoszbialecki commented on src/index.html
> +        <footer>
Wydaje mi się, że footer nie musi być zagnieżdżony w section.

2020-12-29 20:06 UTC, bartoszbialecki commented on src/index.html
> +    <script src="./shared/header/index.js"></script>
Też tutaj nie dodawałbym skryptów, tylko importował wszystko co jest potrzebne w naszym skrypcie wejściowym do aplikacji index.js, który jest dodawany później przez webpacka do index.html

2020-12-29 20:10 UTC, bartoszbialecki commented on src/index.html
>  </html>
Nie wiem czy nawigacja nie powinna być trochę zmieniona. Aktualnie, jak klikniemy w kafelek na głównej stronie, to pojawia się nawigacja ukryta za przyciskiem hamburgera. To jest spoko, ale na wersjach mobilnych, na dużych ekranach wydaje mi się, że lepiej byłoby zrobić zwykłe linki na górze, żeby użytkownik nie musiał niepotrzebnie dwa razy klikać jak chce wybrać inną opcję z menu. Może dałoby radę dostosować menu do rozmiaru ekranu? Poza tym, brakuje linka, aby powrócić do strony głównej, czyli żeby znów widzieć wszystkie główne kafelki.

2020-12-29 20:11 UTC, bartoszbialecki commented on src/shared/header/index.js
> +const btn = document.querySelector('.btnModal')
Obsługa okna modalnego wydaje mi się, że powinna być w osobnym pliku, bo to nie jest odpowiedzialność nagłówka.

2020-12-29 20:36 UTC, hoolek77 commented on src/shared/header/index.js
> +const btn = document.querySelector('.btnModal')
Elementy domu wrzuciłbym do innego pliku, np. DOMElementsModal i tam je wyeksportował jako obiekt, a w tym pliku zaimportował ten obiekt. Wydaje mi się, że kod byłby bardziej przejrzysty wtedy.

2020-12-29 20:45 UTC, hoolek77 commented on src/index.html
> +    <script src="./shared/header/index.js"></script>
To co Bartek mówi, deklaracje funkcji niech zostaną w tym samym miejscu, a w głównym index.js niech będą zaimportowane wszystkie funkcje i tam dodane addEventListenery itd.

2020-12-30 18:41 UTC, pdybowski requested changes

2020-12-30 18:41 UTC, pdybowski commented on src/content/styles/global.css
> +}
**Jedno z wielu rozwiązań:** 

możesz stworzyć w fodlerze src -> 
core
| bootstrap.js
| vendor.js

w vendor.js:
import url('https://fonts.googleapis.com/css2?family=Nunito:wght@300;600;700&family=Roboto+Mono:wght@400;700&display=swap');
import '../../shared/header/nav.css';
import '../../shared/view/view.css';
import '../../shared/footer/footer.css';
import '../../shared/header/popup.css';

w bootstrap.js: 
import './vendor.js'

w src/index.js:
import '[path]/core/bootstrap.js'

(powinno działać jak należy)

2020-12-30 18:41 UTC, pdybowski commented on src/shared/header/index.js
> +const changeViwe = (viewContent) => {
View*

2020-12-30 18:41 UTC, pdybowski commented on src/shared/header/index.js
> +function toggleHamburger() {
dodałbym jeszcze 'Menu' - toggleHamburgerMenu, albo po prostu toggleMenu

2020-12-31 00:47 UTC, pdybowski commented on src/index.html
> +      <section class="modalSection">
Modal można potraktować jako div i wywalić go do body

2020-12-31 00:47 UTC, pdybowski commented on src/shared/header/nav.css
> +    /* width: 650px; */
To ma być zakomentowane? (Tak tylko pytam)

2021-01-03 18:28 UTC, closed without merging