fixing style loader for webpack config
pdybowski/breaking-news pull request #33
Opened 2020-12-29 22:39 UTC by hoolek77

2020-12-29 22:50 UTC, bartoszbialecki approved these changes

2020-12-30 07:55 UTC, bartoszbialecki approved these changes

2020-12-30 09:43 UTC, pdybowski requested changes

2020-12-30 09:43 UTC, pdybowski commented on webpack.config.js
> +  mode: 'production',
to by usunął i zmienił CLI w package.json
`    "start": "webpack --mode=development serve --watch",
    "build": "webpack --mode=production"`.

build jest często domyślną komendą dla serwerów, na których znajeduje się ko źródłowy strony dlatego warto mieć tam mode=production. Natomiast npm run start jest po protsu wykorzystywany do uruchomienia aplikacji przez programistów

2020-12-30 10:35 UTC, pdybowski approved these changes

2020-12-30 10:52 UTC, merged