Weather View
pdybowski/breaking-news pull request #40
Opened 2021-01-06 16:30 UTC by hoolek77

2021-01-06 17:02 UTC, pdybowski requested changes

2021-01-06 17:02 UTC, pdybowski commented on src/views/weather/slider.js
> +  sectionIndex = 0
Można to chyba dodać do konstruktora. Chyba ze korzystamy z tego w innych plikach

2021-01-06 18:42 UTC, pdybowski approved these changes

2021-01-06 20:01 UTC, bartoszbialecki commented on src/views/weather/weatherApi.js
> +      const data = await response.json()
Możesz tutaj skorzystać z klasy bazowej API i użyć tamtej funkcji fetch, wtedy nie musisz robić tego response.json() bo ta funkcja już to robi

2021-01-06 20:05 UTC, bartoszbialecki commented on src/views/weather/weatherApi.js
> +      this.weatherContentProvider.displayResults(data)
Wg mnie, klasa do API powinna zajmować się tylko pobieraniem danych z api zewnętrznego i zwracać te dane. Ja  bym, tą klasę wykorzystywał w klasiew WeatherContentProvider i tam pobrane dane przekazał do klasy widoku i ona tworzy html do wyświetlenia

2021-01-06 20:11 UTC, bartoszbialecki commented on src/views/weather/weatherContentProvider.js
> +            weatherApi.baseUrl,
Jeśli to baseUrl się nie zmienia to nie trzeba go przekazywać tutaj, tylko klasa WeatherAPI może go wewnętrznie używać.

2021-01-06 20:12 UTC, bartoszbialecki commented on src/views/weather/weatherContentProvider.js
> +            weatherApi.apiKey
ApiKey chyba też jest przekazywane w konstruktorze klasy WeatherAPI więc ta klasa może z niego wewnętrznie korzystać i nie musisz go tutaj przekazywać.

2021-01-07 19:26 UTC, ibednorz commented
Poza tym co chłopaki pisali nie widzę nic innego

2021-01-07 20:02 UTC, ibednorz approved these changes

2021-01-07 20:06 UTC, merged